In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
path = 'C:\\Users\\carso\\Downloads\\qb 2.csv'

In [4]:
qb_data = pd.read_csv(path)

In [5]:
qb_data.head()

,Age,Games,Completions,Attempts,Completion Pct,Yards,TD,TD Pct,Int,Int Pct,...,Yards Per Attempt,Adjusted Yards Per Attempt,Yards Per Completion,Yards Per Game,QBR,Sacks,Yards Lost Off Sacks,Sack Pct,Game-winning Drives,Salary in Millions
0,27,17,435,648,67.1,5250,41,6.3,12,1.9,...,8.1,8.5,12.1,308.8,105.2,26,188,3.9,4,45.000000
1,24,17,477,699,68.2,4739,25,3.6,10,1.4,...,6.8,6.9,9.9,278.8,93.2,38,206,5.2,5,52.500000
2,45,17,490,733,66.8,4694,25,3.4,9,1.2,...,6.4,6.5,9.6,276.1,90.7,22,160,2.9,5,15.000000
3,34,17,424,643,65.9,4547,29,4.5,14,2.2,...,7.1,7.0,10.7,267.5,92.5,46,329,6.7,8,40.000000
4,26,16,414,606,68.3,4475,35,5.8,12,2.0,...,7.4,7.6,10.8,279.7,100.8,41,259,6.3,4,3.900012

In [6]:
qb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         100 non-null    int64
 1   Games                       100 non-null    int64
 2   Completions                 100 non-null    int64
 3   Attempts                    100 non-null    int64
 4   Completion Pct              100 non-null    float64
 5   Yards                       100 non-null    int64
 6   TD                          100 non-null    int64
 7   TD Pct                      100 non-null    float64
 8   Int                         100 non-null    int64
 9   Int Pct                     100 non-null    float64
 10  First Downs                 100 non-null    int64
 11  Yards Per Attempt           100 non-null    float64
 12  Adjusted Yards Per Attempt  100 non-null    float64
 13  Yards Per Completion        100 non-null    float64
 14  Yards Per Game              100 non-null    float64
 15  QBR                         100 non-null    float64
 16  Sacks                       100 non-null    int64
 17  Yards Lost Off Sacks        100 non-null    int64
 18  Sack Pct                    100 non-null    float64
 19  Game-winning Drives         100 non-null    int64
 20  Salary in Millions          100 non-null    float64
dtypes: float64(10), int64(11)
memory usage: 16.5 KB

In [7]:
qb_data.describe()

,Age,Games,Completions,Attempts,Completion Pct,Yards,TD,TD Pct,Int,Int Pct,...,Yards Per Attempt,Adjusted Yards Per Attempt,Yards Per Completion,Yards Per Game,QBR,Sacks,Yards Lost Off Sacks,Sack Pct,Game-winning Drives,Salary in Millions
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,28.800000,13.820000,302.160000,461.240000,65.239000,3330.840000,21.540000,4.532000,9.860000,2.221000,...,7.178000,7.084000,11.000000,235.58200,63.514000,29.910000,201.730000,6.303000,2.290000,14.601223
std,5.642551,3.147486,90.363209,129.803201,3.135618,1039.625639,10.347908,1.430256,3.250548,0.710569,...,0.705187,1.067397,0.893975,41.60106,21.905071,10.062527,70.636479,2.060914,1.771235,12.719699
min,22.000000,5.000000,94.000000,140.000000,55.600000,1072.000000,5.000000,1.800000,4.000000,0.800000,...,5.700000,5.100000,9.100000,116.60000,24.800000,9.000000,53.000000,2.100000,0.000000,0.722904
25%,24.000000,12.000000,240.500000,374.250000,63.300000,2504.500000,14.000000,3.600000,7.000000,1.700000,...,6.700000,6.400000,10.400000,209.17500,48.000000,22.000000,149.250000,4.800000,1.000000,4.818047
50%,27.500000,15.000000,305.000000,475.500000,65.900000,3470.500000,20.000000,4.350000,10.000000,2.200000,...,7.200000,7.000000,11.000000,234.30000,61.000000,29.000000,191.500000,6.100000,2.000000,9.763721
75%,32.250000,16.000000,375.000000,560.250000,67.200000,4214.250000,27.500000,5.450000,12.000000,2.700000,...,7.600000,7.825000,11.700000,264.50000,84.025000,36.500000,243.250000,7.600000,3.250000,23.675000
max,45.000000,17.000000,490.000000,733.000000,70.700000,5316.000000,48.000000,9.100000,17.000000,3.800000,...,8.900000,9.600000,13.700000,371.20000,105.500000,55.000000,370.000000,14.700000,8.000000,57.000000

In [8]:
import pandas as pd

#Cleaning dataset and getting rid of missing values
qb_cleaned = qb_data.dropna()

In [9]:
qb_data = qb_cleaned
qb_data.shape

(100, 21)

In [10]:
qb_data.dropna()

,Age,Games,Completions,Attempts,Completion Pct,Yards,TD,TD Pct,Int,Int Pct,...,Yards Per Attempt,Adjusted Yards Per Attempt,Yards Per Completion,Yards Per Game,QBR,Sacks,Yards Lost Off Sacks,Sack Pct,Game-winning Drives,Salary in Millions
0,27,17,435,648,67.1,5250,41,6.3,12,1.9,...,8.1,8.5,12.1,308.8,105.2,26,188,3.9,4,45.000000
1,24,17,477,699,68.2,4739,25,3.6,10,1.4,...,6.8,6.9,9.9,278.8,93.2,38,206,5.2,5,52.500000
2,45,17,490,733,66.8,4694,25,3.4,9,1.2,...,6.4,6.5,9.6,276.1,90.7,22,160,2.9,5,15.000000
3,34,17,424,643,65.9,4547,29,4.5,14,2.2,...,7.1,7.0,10.7,267.5,92.5,46,329,6.7,8,40.000000
4,26,16,414,606,68.3,4475,35,5.8,12,2.0,...,7.4,7.6,10.8,279.7,100.8,41,259,6.3,4,3.900012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22,10,186,290,64.1,1814,11,3.8,5,1.7,...,6.3,6.2,9.8,181.4,44.8,20,136,6.5,0,5.504625
96,36,8,168,252,66.7,1582,6,2.4,8,3.2,...,6.3,5.3,9.4,197.8,28.2,22,139,8.0,1,20.300000
97,23,7,148,241,61.4,1439,5,2.1,7,2.9,...,6.0,5.1,9.7,205.6,24.8,20,141,7.7,1,5.416804
98,29,6,94,140,67.1,1096,7,5.0,5,3.6,...,7.8,7.2,11.7,182.7,54.0,11,77,7.3,0,23.800000
99,31,5,111,179,62.0,1072,7,3.9,5,2.8,...,6.0,5.5,9.7,214.4,29.8,9,53,4.8,0,1.187500

In [11]:
#Business problem 1: Can we predict if a QB should be making an above average salary? 
#If so, this could help us with evaluating QB's and what stats are indicators of higher value in contracts.
qb_data.loc[qb_data['Salary in Millions'] < 14.6, 'Success'] = 0
qb_data.loc[qb_data['Salary in Millions'] > 14.6, 'Success'] = 1

In [34]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, r2_score

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 6)

In [36]:
X = qb_data.drop(qb_data[["Success"]], axis = 1)
Y = qb_data["Success"]

In [37]:
clf = LogisticRegression(random_state=0).fit(X_train, Y_train)

clf.predict(X_test)

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0.])

In [38]:
print("Model score on testing set: ", clf.score(X_test,Y_test))

Model score on testing set:  0.9333333333333333

In [39]:
#Business problem 2: What are good indicators of a QB's health(games played above average)?
#If we find a way to predict this, we can see if we need to use strategy to help minimize risk during the game

In [40]:
path1 = 'C:\\Users\\carso\\Downloads\\qb games.csv'
qb_games = pd.read_csv(path1)

In [41]:
X1 = qb_games.drop(qb_games[["Games"]], axis = 1)
Y1 = qb_games["Games"]

In [42]:
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, test_size = 0.3, random_state = 6)

In [43]:
# Create a Linear Regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X1_train, Y1_train)

# Make predictions on the test data
y_pred = model.predict(X1_test)

# Calculate and print the model's performance metrics
mse = mean_squared_error(Y1_test, y_pred)
r2 = r2_score(Y1_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared (Coefficient of Determination): {r2}')

for i, predicted_value in enumerate(y_pred):
    print(f"Row {i + 1}: Predicted Value = {predicted_value}")

Mean Squared Error: 3.204336592068642
R-squared (Coefficient of Determination): 0.7697298839937897
Row 1: Predicted Value = 13.793188034349917
Row 2: Predicted Value = 16.129508194431878
Row 3: Predicted Value = 17.36613494725783
Row 4: Predicted Value = 16.685896998712117
Row 5: Predicted Value = 9.219087591522037
Row 6: Predicted Value = 14.704957268092853
Row 7: Predicted Value = 11.878608710294934
Row 8: Predicted Value = 14.981736411586224
Row 9: Predicted Value = 16.161201987807974
Row 10: Predicted Value = 11.518352588784357
Row 11: Predicted Value = 9.150112801851819
Row 12: Predicted Value = 16.66342654913396
Row 13: Predicted Value = 18.045896378535158
Row 14: Predicted Value = 16.371280131126028
Row 15: Predicted Value = 17.649903050704783
Row 16: Predicted Value = 12.41642271928574
Row 17: Predicted Value = 11.316993966531975
Row 18: Predicted Value = 8.054969941094924
Row 19: Predicted Value = 15.761957114426155
Row 20: Predicted Value = 12.333605787373807
Row 21: Predicted Value = 15.581619826712679
Row 22: Predicted Value = 18.725137913322843
Row 23: Predicted Value = 16.560302783466568
Row 24: Predicted Value = 14.538232017725194
Row 25: Predicted Value = 9.448957697201141
Row 26: Predicted Value = 12.770001380983812
Row 27: Predicted Value = 14.81592709486656
Row 28: Predicted Value = 14.444589619109165
Row 29: Predicted Value = 14.354543086050493
Row 30: Predicted Value = 9.315967688569097